apiVersion: v1
kind: Pod
metadata:
  name: hw1
spec:
  containers:
  - name: nginx
    image: hrorel/kubernetes-intro:1.0
    ports:
    - containerPort: 8000
    volumeMounts:
      - name: app
        mountPath: "/app"
  initContainers:
  - name: init-index
    image: busybox:1.28
    command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
    volumeMounts:
      - name: app
        mountPath: "/app"
  volumes:
  - name: app
    emptyDir: {}    